name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
        pytorch-version: ["2.0.0", "2.8.0"]
        exclude:
          - python-version: "3.13"
            pytorch-version: "2.0.0"

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install torch==${{ matrix.pytorch-version }} --index-url https://download.pytorch.org/whl/cpu
          python -m pip install .

      - name: Test with Unittest
        run: |
          python -W "ignore:Failed to initialize NumPy:UserWarning" \
            -m unittest discover -s test -p "*_test.py" -v

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
